### ISSUE TITLE
Neither id token nor userinfo contained an email

### ISSUE THREAD

**Issue by HaraldRuppert** [Timshel/OIDCWarden#27]
Hi,
I'm using a fresh installation of oidcwarden (tried "latest" and "testing").

>      - SSO_ENABLED=true
>      - SSO_FRONTEND='override'
>      - SSO_AUTHORITY=https://auth.{my-domain.tld}/application/o/vaultwarden/
>      - SSO_SCOPES='email profile offline_access'
>      - SSO_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>      - SSO_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>      - SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION=true
>      - SSO_DEBUG_TOKENS=true
>      - LOG_LEVEL=debug

The JWT payload preview in Authentik looks correct

> ...
>     "email": "{me@my-domain.tld}",
>     "email_verified": true,
>     "name": "{me}",
>     "given_name": "{me}",
>     "preferred_username": "{me@my-domain.tld}",
>     "nickname": "{me@my-domain.tld}",
>     "groups": [
>         "authentik Admins"
>     ]

In the log I can see

`[2025-04-23 09:12:37.384][oidcwarden::sso][DEBUG] Refresh token: None
[2025-04-23 09:12:37.384][oidcwarden::sso][DEBUG] Expiration time: Some(300s)
[2025-04-23 09:12:37.385][oidcwarden::sso][ERROR] Neither id token nor userinfo contained an email
[2025-04-23 09:12:37.385][response][INFO] (login) POST /identity/connect/token => 400 Bad Request
`

Other applications have the provider configured identically and report the email correct. 

The selected scopes in advanced protocol settings contains email, offline_access, openid and profile

If I decode the JWT token from the debug log it appears that the email is not included however

Any idea?

Thanks

**Comment by Timshel** [comment]
Hey,

That's a strange one, I recently tested Authentik for another issue and had no such problem.
You can check the docker compose I used [here](https://github.com/Timshel/vaultwarden/blob/main/docker/authentik/README.md).

If you logged the `id_token` using `SSO_DEBUG_TOKENS=true` and the email is not present I would expect the issue to be with Authentik.

I'm not using Authentik, so I won't be able to help much with it, sorry :(.

**Comment by HaraldRuppert** [comment]
Thanks for the swift update. That appears to be the case, there's no email field, neither in the access token nor the id token.

Is there a way to change to change the username mapping from email to preferred_username?

**Comment by Timshel** [comment]
Hey,
An email is needed, it cannot be replaced by a username.

**Comment by PaddyPat** [comment]
Remove in docker compose:
 - SSO_SCOPES='email profile offline_access'

than it works again

**Comment by HaraldRuppert** [comment]
@PaddyPat Holy guacamoly, this works now. Thanks a lot!

@Timshel maybe something to add into the documentation :-)

Thanks again to everyone here.

**Comment by Timshel** [comment]
Strange, which image are you using ? 
I'll test again, but I don't believe I had the issue with `goauthentik/server:2025.2.3`.

**Comment by PaddyPat** [comment]
Same issue via pocketid

https://github.com/pocket-id/pocket-id 

latest release 0.49

**Comment by HaraldRuppert** [comment]
Thanks, here are my complete docker compose files:

**Authentik:**
```
---
version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - authentik-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
  #  env_file:
  #    - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - authentik-redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    volumes:
      - authentik-media:/media
      - authentik-custom-templates:/templates
 #   env_file:
 #     - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-media:/media
      - authentik-certs:/certs
      - authentik-custom-templates:/templates
 #   env_file:
 #     - .env
    depends_on:
      - postgresql
      - redis

volumes:
  authentik-postgresql:
    external: true
  authentik-redis:
    external: true
  authentik-media:
    external: true
  authentik-certs:
    external: true
  authentik-custom-templates:
    external: true
```

**Vaultwarden:**

```
version: "3"
services:
  vaultwarden:
    image: timshel/oidcwarden:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 9445:80 #map any custom port to use (replace 9445 not 80)
    volumes:
     - vaultwarden-data:/data:rw
    environment:
#     - ROCKET_TLS={certs="/ssl/certs/certs.pem",key="/ssl/private/key.pem"}  // Environment variable is specific to the Rocket web server
#     - DISABLE_ADMIN_TOKEN=true
     - ADMIN_TOKEN=$$argon2id$$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     - WEBSOCKET_ENABLED=true
     - SIGNUPS_ALLOWED=true
     - SMTP_HOST=xxxxxxxxxxxxxxxxxx
     - SMTP_FROM=xxxxxxxxxxxxxxxxxxxx
     - SMTP_PORT=587
     - SMTP_SSL=starttls
     - SMTP_USERNAME=xxxxxxxxxxxxxxxxxxxxxxxxx
     - SMTP_PASSWORD=xxxxxxxxxxxxxxxx
     - DOMAIN=https://xxxxxxxxxxx
     - SSO_ENABLED=true
     - SSO_FRONTEND='override'
     - SSO_AUTHORITY=https://xxxxxxxxxxxxxx/application/o/vaultwarden/
#     - SSO_SCOPES='email profile offline_access'
     - SSO_CLIENT_ID=xxxxxxxxxxxxxxxxx
     - SSO_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxx
     - SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION=true
#   - SSO_DEBUG_TOKENS=true
#   - LOG_LEVEL=debug

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/

volumes:
  vaultwarden-data:
    external: true
  vaultwarden-rclone-data:
    external: true
```
