### ISSUE TITLE
[BUG] email_verified claim not being fetched from UserInfo Endpoint

### ISSUE THREAD

**Issue by hendrik1120** [Timshel/OIDCWarden#31]
Hi,

I recently noticed a bug when trying to integrate authelia with oidcwarden.

Oidcwarden seems to correctly fetch claims from the UserInfo endpoint if they are not in the ID-Token, however this is not the case with the `email_verified` claim. A user trying to register will be denied access with the following error message:

```
Error
Your provider does not send email verification status. You will need to change the server configuration (check `SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION`) to log in.
```

If I explicitly configure authelia to include the `email_verified` claim in the ID-Token this issue is resolved.

It shouldn't be necessary to explicitly include a claim in the ID-Token because according to the oidc specification, the relying party not should make any assumptions about a claim being in the ID-Token. 

### oidcwarden configuration:
```yml
services:
  oidcwarden:
    environment:
      - SSO_ENABLED=true
      - SSO_ONLY=true
      - SSO_AUTHORITY=https://auth.example.com
      - SSO_SCOPES=profile email offline_access
      - SSO_PKCE=true
      - SSO_CLIENT_ID=oidcwarden
      - SSO_CLIENT_SECRET=insecure_secret
```
